//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class chrysallis_grupo3Entities3 : DbContext
    {
        public chrysallis_grupo3Entities3()
            : base("name=chrysallis_grupo3Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assistir> Assistir { get; set; }
        public virtual DbSet<Comunitat> Comunitat { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<Notificacions> Notificacions { get; set; }
        public virtual DbSet<Esdeveniment> Esdeveniment { get; set; }
        public virtual DbSet<Socis> Socis { get; set; }
    }
}
