'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ApiChrys

    Partial Public Class Comunitat
        Public Property id As Integer
        Public Property nombre As String
    
        Public Overridable Property Esdeveniment As ICollection(Of Esdeveniment) = New HashSet(Of Esdeveniment)
        Public Overridable Property Socis As ICollection(Of Socis) = New HashSet(Of Socis)
        Public Overridable Property Socis1 As ICollection(Of Socis) = New HashSet(Of Socis)
    
    End Class

End Namespace
