'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ApiChrys

    Partial Public Class Esdeveniment
        Public Property id As Integer
        Public Property fechaInicio As Date
        Public Property horaInicio As System.TimeSpan
        Public Property NombreEvento As String
        Public Property Direccio As String
        Public Property id_Comunitat As Integer
        Public Property fechaFin As Date
        Public Property horaFin As Nullable(Of System.TimeSpan)
    
        Public Overridable Property Assistir As ICollection(Of Assistir) = New HashSet(Of Assistir)
        Public Overridable Property Comunitat As Comunitat
        Public Overridable Property Documents As ICollection(Of Documents) = New HashSet(Of Documents)
        Public Overridable Property Notificacions As ICollection(Of Notificacions) = New HashSet(Of Notificacions)
    
    End Class

End Namespace
