'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace ApiChrys

    Partial Public Class chrysallis_grupo3Entities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=chrysallis_grupo3Entities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Assistir() As DbSet(Of Assistir)
        Public Overridable Property Comunitat() As DbSet(Of Comunitat)
        Public Overridable Property Documents() As DbSet(Of Documents)
        Public Overridable Property Esdeveniment() As DbSet(Of Esdeveniment)
        Public Overridable Property Notificacions() As DbSet(Of Notificacions)
        Public Overridable Property Socis() As DbSet(Of Socis)
    
    End Class

End Namespace
