'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ApiChrys

    Partial Public Class Notificacions
        Public Property id As Integer
        Public Property antelacio As Nullable(Of Date)
    
        Public Overridable Property Esdeveniment As ICollection(Of Esdeveniment) = New HashSet(Of Esdeveniment)
    
    End Class

End Namespace
