'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ApiChrys

    Partial Public Class Socis
        Public Property id As Integer
        Public Property telefon As String
        Public Property mail As String
        Public Property nom As String
        Public Property cognoms As String
        Public Property contrasenya As String
        Public Property actiu As Boolean
        Public Property administrador As Boolean
        Public Property id_comunitat_admin As Nullable(Of Integer)
        Public Property DNI As String
    
        Public Overridable Property Assistir As ICollection(Of Assistir) = New HashSet(Of Assistir)
        Public Overridable Property Comunitat As Comunitat
        Public Overridable Property Comunitat1 As ICollection(Of Comunitat) = New HashSet(Of Comunitat)
    
    End Class

End Namespace
