//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIchris
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class chrysallis_grupo3Entities1 : DbContext
    {
        public chrysallis_grupo3Entities1()
            : base("name=chrysallis_grupo3Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assistir> Assistirs { get; set; }
        public virtual DbSet<Comunitat> Comunitats { get; set; }
        public virtual DbSet<Esdeveniment> Esdeveniments { get; set; }
        public virtual DbSet<Soci> Socis { get; set; }
    }
}
